### Variables
@apiUrl = http://localhost
@port = 4000
@baseUrl = {{apiUrl}}:{{port}}/students

###
# CREATE - Agregar nuevo estudiante
POST {{baseUrl}}
Content-Type: application/json

{
    "id": "9",
    "nombre": "Antonio Ramón",
    "nivel": "intermedio",
    "activo": true
}

###
# READ ALL - Obtener todos los estudiantes
GET {{baseUrl}}


###
# READ by ID - Obtener un estudiante por su ID (Id: 1)
GET {{baseUrl}}/1